RT-12219: LevelCreditApiClient first part
levelcredit/levelcredit-api-php pull request #1
Opened 2021-01-19 09:42 UTC by yurez

2021-01-19 11:03 UTC, tatyana-shmatchenko requested changes
Looks great @yurez !
Really like it :+1: 
Let's discuss logs and doctypes.

2021-01-19 11:03 UTC, tatyana-shmatchenko commented on src/LoggableBehavior/DefaultLogHandler.php
> +namespace LevelCredit\LevelCreditApi\LoggableBehavior;
Let's discuss this namespace.

2021-01-19 23:54 UTC, caryp requested changes
Looking very good, @yurez ! I only did a high-level review. A couple comments added.  Also please add at least enough documentation in the readme to tell me how to install and make a simple request.  Ideally a way to run the tests too.

2021-01-19 23:54 UTC, caryp commented on src/LevelCreditApiClient.php
> +        Serializer $serializer,
Why supply a serializer in the constructor if you are just going to default it?  Why not use an accessor method to set this if you want to use something non-default?

2021-01-19 23:54 UTC, caryp commented on composer.json
> +  "description": "LevelCredit Distributed API Client Library for PHP",
please remove "Distributed"

2021-01-19 23:54 UTC, caryp commented on composer.json
> +  "license": "MIT",
I am checking on what this license should be with Shivan.  Good enough for now, but might need to change.

2021-01-21 16:46 UTC, tatyana-shmatchenko approved these changes
Great job :+1:

2021-01-21 16:46 UTC, tatyana-shmatchenko commented on src/Enum/UserStatus.php
> +    public const INVITE = 'invite';
Should we add any other statuses?

2021-01-21 16:46 UTC, tatyana-shmatchenko commented on src/Logging/DefaultLogHandler.php
> +    private const PRIVATE_FIELDS_REPLACEMENT = [
Please add client_secret.

2021-01-21 16:46 UTC, tatyana-shmatchenko commented on src/Serializer/Serializer.php
> +    protected const FAILED_STATUS_ENTRYPOINT = 400;
ENTRYPOINT -> ENTRY_POINT

2021-01-21 16:49 UTC, yurez commented on src/Enum/UserStatus.php
> +    public const INVITE = 'invite';
We are not supported right now other statuses in the api.

2021-01-21 17:38 UTC, yurez commented
@caryp it's ready for your review, readme file will be added in next sprint

2021-01-21 19:54 UTC, caryp commented
@yurez I reviewed 2days ago. please address my comments. thank you

2021-01-25 15:11 UTC, tatyana-shmatchenko commented
Discussed with @caryp on the standup that this is approved! Merging.

2021-01-25 15:12 UTC, merged